# Generated by Django 4.0 on 2021-12-08 17:04

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('legal_entity', '__first__'),
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Departments',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('id_department', models.IntegerField(blank=True, max_length=7, unique=True, validators=[django.core.validators.RegexValidator(message='identification number (always ends with 01)', regex='\\d*(03)$')])),
                ('name', models.CharField(blank=True, max_length=255)),
                ('id_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.client')),
                ('id_legal_entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='legal_entity.legalentity')),
            ],
        ),
    ]
